### ISSUE TITLE
Add a list of issues to be solved

### ISSUE THREAD

**Issue by Ekeuwei** [Ekeuwei/sportmonks#2]
### TODO
*Add a list of issues this repo aims to solve*

- [ ] Request match fixtures from sportmonks
- [ ] Get H2H match details
- [ ] Request live data from sportmonk
- [ ] Get predictions from the sportmonk api
:tada: :ok_man: :confetti_ball:

cc @ekeuwei
